# Generated by Django 3.2.25 on 2025-03-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_count_habit_current_count_habit_target_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habit',
        ),
    ]
