# Generated by Django 3.2.25 on 2025-03-02 15:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('habit_type', models.CharField(choices=[('measurable', 'Measurable'), ('non-measurable', 'Non-Measurable')], max_length=20)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
