# Generated by Django 5.1.6 on 2025-03-02 17:38

import habit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_reset_date',
            field=models.DateField(default=habit.models.get_today),
        ),
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(default=habit.models.get_today),
        ),
    ]
