# Generated by Django 5.1.6 on 2025-03-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_last_reset_date_alter_habit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
