# Generated by Django 5.1.6 on 2025-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_habit_last_completed_habit_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed_dates',
            field=models.JSONField(default=list),
        ),
    ]
